name: ie-bank-uat

on:
  pull_request:
    branches:
      - main  # This will trigger the workflow when a pull request to 'main' is opened or merged
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build -- --mode production --dest dist-prod

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: uat-build
        path: dist-prod
